# Generated by Django 2.0.3 on 2021-03-24 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0109_auto_20210324_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cassette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlative', models.PositiveIntegerField(verbose_name='correlative')),
                ('build_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organs', models.ManyToManyField(related_name='cassettes', to='backend.Organ')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cassettes', to='backend.Unit')),
            ],
        ),
    ]
