# Generated by Django 2.1.15 on 2021-05-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0118_auto_20210506_1124"),
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CassetteOrgan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "lab_cassette_organ",
            },
        ),
        migrations.RemoveField(
            model_name="cassette",
            name="organs",
        ),
        migrations.AddField(
            model_name="cassette",
            name="organs",
            field=models.ManyToManyField(
                related_name="cassettes",
                through="lab.CassetteOrgan",
                to="backend.Organ",
            ),
        ),
        migrations.AddField(
            model_name="cassetteorgan",
            name="cassette",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lab.Cassette"
            ),
        ),
        migrations.AddField(
            model_name="cassetteorgan",
            name="organ",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backend.Organ"
            ),
        ),
    ]
