# Generated by Django 2.0.3 on 2021-03-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0109_auto_20210324_1025'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('backend.entryform',),
        ),
        migrations.AlterField(
            model_name='cassette',
            name='processed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
