# Generated by Django 2.0.3 on 2021-03-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20210325_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassette',
            name='build_at',
            field=models.DateTimeField(null=True),
        ),
    ]
