# Generated by Django 2.1.15 on 2021-06-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_laboratory_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='process',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Desactivar'),
        ),
        migrations.AddField(
            model_name='process',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Desactivar'),
        ),
    ]
