# Generated by Django 2.1.15 on 2021-04-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20210326_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-entryform_type_id', '-created_at']},
        ),
    ]
