# Generated by Django 2.1.15 on 2021-06-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lab', '0004_auto_20210602_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Desactivado'),
        ),
        migrations.AlterField(
            model_name='process',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Desactivado'),
        ),
        migrations.AlterField(
            model_name='process',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Process'),
        ),
        migrations.AddField(
            model_name='processitem',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_items', to='lab.Process'),
        ),
    ]
