# Generated by Django 2.1.15 on 2021-04-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20210413_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cassette',
            name='processed_at',
        ),
    ]
