# Generated by Django 2.1.15 on 2021-04-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0109_auto_20210324_1025'),
        ('lab', '0005_remove_cassette_processed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cassette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='lab.Cassette')),
                ('stain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='backend.Stain')),
            ],
        ),
    ]
