# Generated by Django 2.1.15 on 2021-06-08 10:51

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20210603_1127'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='processitem',
            managers=[
                ('items', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='entry_type',
            field=models.SmallIntegerField(choices=[(1, 'Tubo'), (2, 'Cassette'), (3, 'Bloque'), (4, 'Slide s/teñir'), (5, 'Slide teñido'), (6, 'Vivo'), (7, 'Muerto')], default=1),
        ),
        migrations.AddField(
            model_name='processitem',
            name='processed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
