# Generated by Django 2.1.15 on 2021-04-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='correlative',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cassette',
            name='correlative',
            field=models.PositiveIntegerField(),
        ),
    ]
