# Generated by Django 2.1.15 on 2021-04-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0109_auto_20210324_1025'),
        ('lab', '0007_auto_20210422_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='backend.Unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='cassette',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='lab.Cassette'),
        ),
    ]
