# Generated by Django 2.1.15 on 2021-06-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_auto_20210609_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassette',
            name='processed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
