# Generated by Django 2.1.15 on 2021-06-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_auto_20210624_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='process',
            field=models.ManyToManyField(related_name='process', through='lab.ProcessTree', to='lab.Process'),
        ),
    ]
