# Generated by Django 2.1.15 on 2021-06-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_auto_20210624_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessItem',
            new_name='ProcessUnit',
        ),
    ]
