# Generated by Django 2.1.15 on 2021-07-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_process_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='parent',
        ),
    ]
