# Generated by Django 2.1.15 on 2021-07-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0124_auto_20210702_1152'),
        ('lab', '0021_treeprocess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TreeProcess',
            new_name='Tree',
        ),
    ]
