# Generated by Django 2.1.15 on 2021-07-07 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0022_auto_20210707_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.TreeProcess')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Process')),
            ],
        ),
        migrations.AddField(
            model_name='tree',
            name='entry_type',
            field=models.CharField(blank=True, choices=[(1, 'Tubo'), (2, 'Cassette'), (3, 'Bloque'), (4, 'Slide s/teñir'), (5, 'Slide teñido'), (6, 'Vivo'), (7, 'Muerto')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Exam'),
        ),
        migrations.AddField(
            model_name='treeprocess',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Tree'),
        ),
    ]
