# Generated by Django 2.1.15 on 2021-08-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0124_auto_20210702_1152'),
        ('lab', '0024_auto_20210708_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'SIN CORREGIR'), (1, 'CORREGIDO')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Organ')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('backend.analysisform',),
        ),
    ]
