# Generated by Django 2.1.15 on 2021-08-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0025_analysis_unitdifference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdifference',
            name='status',
            field=models.IntegerField(choices=[(0, 'SIN CORREGIR'), (1, 'CORREGIDO')], default=0),
        ),
    ]
