# Generated by Django 2.1.15 on 2021-08-05 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lab", "0026_auto_20210804_1521"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitdifference",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unitdifference",
            name="status_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="unitdifference",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "SIN CORREGIR"), (1, "CORREGIDO")], default=0
            ),
        ),
    ]
