# Generated by Django 2.1.15 on 2021-08-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0027_auto_20210805_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdifference',
            name='status_change_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
