# Generated by Django 2.1.15 on 2021-08-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0128_auto_20210824_1330'),
        ('lab', '0029_auto_20210817_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('backend.unit',),
        ),
    ]
