# Generated by Django 2.1.15 on 2021-05-12 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0118_auto_20210506_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(0, 'FORMATO'), (1, 'REVISION'), (2, 'ENVIO'), (3, 'FINALIZADO')], default=0, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('backend.analysisform',),
        ),
        migrations.AddField(
            model_name='stage',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='backend.AnalysisForm'),
        ),
        migrations.AddField(
            model_name='stage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_stages', to=settings.AUTH_USER_MODEL),
        ),
    ]
