# Generated by Django 2.1.15 on 2021-05-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20210520_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisMailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Analysis')),
            ],
        ),
        migrations.RenameField(
            model_name='maillist',
            old_name='client',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='analysismaillist',
            name='mail_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.MailList'),
        ),
        migrations.AddField(
            model_name='maillist',
            name='analysis',
            field=models.ManyToManyField(related_name='mailing_lists', through='review.AnalysisMailList', to='review.Analysis'),
        ),
    ]
