# Generated by Django 2.1.15 on 2021-05-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20210527_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
