# Generated by Django 2.1.15 on 2021-05-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20210527_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillist',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Desactivado'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Desactivado'),
        ),
    ]
