# Generated by Django 2.1.15 on 2021-05-27 11:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_auto_20210527_1114'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='maillist',
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='recipient',
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
    ]
