# Generated by Django 2.1.15 on 2021-05-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_auto_20210527_1115'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='maillist',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='recipient',
            managers=[
            ],
        ),
    ]
