# Generated by Django 2.1.15 on 2021-06-04 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_auto_20210527_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('mail_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.MailList')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Recipient')),
            ],
        ),
    ]
