# Generated by Django 2.1.15 on 2021-06-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_recipientmail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipientmail',
            table='review_recipient_mail',
        ),
    ]
