# Generated by Django 2.1.15 on 2021-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0014_auto_20210604_1447"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maillist",
            name="recipients",
        ),
        migrations.AddField(
            model_name="maillist",
            name="recipients",
            field=models.ManyToManyField(
                related_name="mailing_lists",
                through="review.RecipientMail",
                to="review.Recipient",
            ),
        ),
    ]
