# Generated by Django 2.1.15 on 2021-06-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_auto_20210604_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientmail',
            name='mail_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients_emails', to='review.MailList'),
        ),
        migrations.AlterField(
            model_name='recipientmail',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_lists', to='review.Recipient'),
        ),
    ]
