# Generated by Django 2.0.3 on 2018-04-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures'),
        ),
    ]
