# Generated by Django 2.0.3 on 2018-04-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_auto_20180409_1755'),
        ('accounts', '0002_auto_20180402_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.Actor'),
        ),
    ]
