# Generated by Django 2.0.3 on 2021-02-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_is_pathologist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.IntegerField(choices=[(1, 'ES'), (2, 'EN')], default=1, verbose_name='Lenguage'),
        ),
    ]
