# Generated by Django 2.1.15 on 2021-05-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_reviewer',
            field=models.BooleanField(default=False, verbose_name='¿Es revisor?'),
        ),
    ]
