# Generated by Django 2.0.3 on 2018-04-13 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.Flow'),
        ),
    ]
