# Generated by Django 2.0.3 on 2018-04-16 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_auto_20180413_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='workflows.Flow'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='type_permission',
            field=models.CharField(choices=[('w', 'Write'), ('a', 'Authorize'), ('r', 'Read')], max_length=1),
        ),
    ]
