# Generated by Django 2.0.3 on 2018-04-17 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_auto_20180416_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='actors',
        ),
        migrations.AddField(
            model_name='actor',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.Step'),
        ),
        migrations.AddField(
            model_name='step',
            name='route',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
