# Generated by Django 2.0.3 on 2018-04-17 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_auto_20180417_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='state',
        ),
        migrations.AddField(
            model_name='form',
            name='state',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflows.State'),
            preserve_default=False,
        ),
    ]
