# Generated by Django 2.0.3 on 2018-04-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_auto_20180417_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.State'),
        ),
    ]
