# Generated by Django 2.0.3 on 2018-04-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_auto_20180419_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='step',
        ),
        migrations.AddField(
            model_name='step',
            name='actors',
            field=models.ManyToManyField(to='workflows.Actor'),
        ),
    ]
