# Generated by Django 2.0.3 on 2018-04-23 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180423_1607'),
        ('workflows', '0009_auto_20180423_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile'),
        ),
    ]
