# Generated by Django 2.0.3 on 2018-05-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_actor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='tag',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
