# Generated by Django 2.0.3 on 2018-05-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_step_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='permission',
        ),
        migrations.AddField(
            model_name='actor',
            name='permission',
            field=models.ManyToManyField(to='workflows.Permission'),
        ),
    ]
