# Generated by Django 2.0.3 on 2018-06-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0013_step_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('flow', 'order')},
        ),
    ]
