# Generated by Django 2.0.3 on 2018-06-07 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0014_auto_20180607_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order']},
        ),
    ]
