# Generated by Django 2.0.3 on 2019-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0018_FormReopened'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
