# Generated by Django 2.0.3 on 2020-06-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0020_auto_20200423_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='deleted',
        ),
    ]
