# Generated by Django 2.0.3 on 2021-03-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0021_remove_form_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='reception_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='reception_finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
