# Generated by Django 2.1.15 on 2021-08-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0022_auto_20210322_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='cancelled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='reception_finished',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='reception_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
