# Generated by Django 2.0.3 on 2018-04-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_organ'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type_customer',
            field=models.CharField(blank=True, choices=[('l', 'Laboratory'), ('s', 'Salmon Farming')], max_length=1, null=True),
        ),
    ]
