# Generated by Django 2.0.3 on 2018-04-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_customer_type_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='cage',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='entryform',
            name='group',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='entryform',
            name='no_container',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entryform',
            name='no_fish',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
