# Generated by Django 2.0.3 on 2018-04-17 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20180416_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage', models.CharField(blank=True, max_length=250, null=True)),
                ('no_fish', models.IntegerField(blank=True, null=True)),
                ('no_container', models.IntegerField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='entryform',
            old_name='no_container',
            new_name='no_order',
        ),
        migrations.RemoveField(
            model_name='entryform',
            name='cage',
        ),
        migrations.RemoveField(
            model_name='entryform',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='entryform',
            name='group',
        ),
        migrations.RemoveField(
            model_name='entryform',
            name='no_fish',
        ),
        migrations.AddField(
            model_name='identification',
            name='entryform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.EntryForm'),
        ),
    ]
