# Generated by Django 2.0.3 on 2018-05-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20180417_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cassettes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(blank=True, max_length=250, null=True)),
                ('organs', models.ManyToManyField(to='backend.Organ')),
            ],
        ),
        migrations.AddField(
            model_name='entryform',
            name='center',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='no_order',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
