# Generated by Django 2.0.3 on 2018-05-10 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20180503_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_fish', models.IntegerField(blank=True, null=True)),
                ('entryform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.EntryForm')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Exam')),
                ('organs', models.ManyToManyField(to='backend.Organ')),
            ],
        ),
        migrations.CreateModel(
            name='Cassette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(blank=True, max_length=250, null=True)),
                ('organs', models.ManyToManyField(to='backend.Organ')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exams', models.ManyToManyField(to='backend.Exam')),
            ],
        ),
        migrations.RemoveField(
            model_name='cassettes',
            name='organs',
        ),
        migrations.DeleteModel(
            name='Cassettes',
        ),
        migrations.AddField(
            model_name='cassette',
            name='slides',
            field=models.ManyToManyField(to='backend.Slide'),
        ),
    ]
