# Generated by Django 2.0.3 on 2018-05-17 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20180510_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassette',
            name='entryform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.EntryForm'),
        ),
    ]
