# Generated by Django 2.0.3 on 2018-05-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_cassette_cassette_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='stain',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
