# Generated by Django 2.0.3 on 2018-05-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_exam_stain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('slice_name',
                 models.CharField(blank=True, max_length=250, null=True)),
                ('start_block', models.DateTimeField(blank=True, null=True)),
                ('end_block', models.DateTimeField(blank=True, null=True)),
                ('start_slice', models.DateTimeField(blank=True, null=True)),
                ('end_slice', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='slide',
            name='exams',
        ),
        migrations.RemoveField(
            model_name='cassette',
            name='slides',
        ),
        migrations.DeleteModel(name='Slide', ),
        migrations.AddField(
            model_name='cassette',
            name='slices',
            field=models.ManyToManyField(to='backend.Slice'),
        ),
    ]
