# Generated by Django 2.0.3 on 2018-06-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20180530_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analysis',
            new_name='AnalysisForm',
        ),
    ]
