# Generated by Django 2.0.3 on 2018-06-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20180607_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='end_diagnostic',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slice',
            name='slice_store',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='slice',
            name='start_diagnostic',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
