# Generated by Django 2.0.3 on 2018-06-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20180607_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassette',
            name='identifications',
            field=models.ManyToManyField(to='backend.Identification'),
        ),
    ]
