# Generated by Django 2.0.3 on 2018-06-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20180608_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='box_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
