# Generated by Django 2.0.3 on 2018-06-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_slice_box_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('organs', models.ManyToManyField(to='backend.Organ')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('organs', models.ManyToManyField(to='backend.Organ')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticIntensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('organs', models.ManyToManyField(to='backend.Organ')),
            ],
        ),
        migrations.CreateModel(
            name='OrganLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('organs', models.ManyToManyField(to='backend.Organ')),
            ],
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('organs', models.ManyToManyField(to='backend.Organ')),
            ],
        ),
    ]
