# Generated by Django 2.0.3 on 2018-06-18 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_diagnostic_diagnosticdistribution_diagnosticintensity_organlocation_pathology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.AnalysisForm')),
                ('diagnostic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Diagnostic')),
                ('diagnostic_distribution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.DiagnosticDistribution')),
                ('diagnostic_intensity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.DiagnosticIntensity')),
                ('organ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Organ')),
                ('organ_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.OrganLocation')),
                ('pathology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Pathology')),
            ],
        ),
    ]
