# Generated by Django 2.0.3 on 2018-06-18 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='slice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Slice'),
        ),
    ]
