# Generated by Django 2.0.3 on 2018-06-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_report_slice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cassette',
            name='processor_loaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
