# Generated by Django 2.0.3 on 2018-09-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_cassette_processor_loaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='no_caso',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
