# Generated by Django 2.0.3 on 2018-09-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_entryform_no_caso'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='flag_subflow',
            field=models.BooleanField(default=False),
        ),
    ]
