# Generated by Django 2.0.3 on 2018-10-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_entryform_flag_subflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente'},
        ),
        migrations.AlterModelOptions(
            name='diagnostic',
            options={'verbose_name': 'Patología', 'verbose_name_plural': 'Patologías'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Exámen', 'verbose_name_plural': 'Exámenes'},
        ),
        migrations.AlterModelOptions(
            name='fixative',
            options={'verbose_name': 'Fijador', 'verbose_name_plural': 'Fijadores'},
        ),
        migrations.AlterModelOptions(
            name='organ',
            options={'verbose_name': 'Órgano', 'verbose_name_plural': 'Órganos'},
        ),
        migrations.AlterModelOptions(
            name='pathology',
            options={'verbose_name': 'Patología', 'verbose_name_plural': 'Patologías'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Compañía / Empresa'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type_customer',
            field=models.CharField(blank=True, choices=[('l', 'Laboratorio'), ('s', 'Salmonera')], max_length=1, null=True, verbose_name='Tipo de Cliente'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='organs',
            field=models.ManyToManyField(to='backend.Organ', verbose_name='Órganos'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='stain',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Tinción'),
        ),
        migrations.AlterField(
            model_name='fixative',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='organlocation',
            name='organs',
            field=models.ManyToManyField(to='backend.Organ', verbose_name='Órganos'),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Patología'),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='organs',
            field=models.ManyToManyField(to='backend.Organ', verbose_name='Órganos'),
        ),
    ]
