# Generated by Django 2.0.3 on 2018-10-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20181025_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type_customer',
            field=models.CharField(blank=True, choices=[('l', 'Laboratorio'), ('e', 'Empresa')], max_length=1, null=True, verbose_name='Tipo de Cliente'),
        ),
    ]
