# Generated by Django 2.0.3 on 2018-11-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20181030_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisform',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
