# Generated by Django 2.0.3 on 2018-11-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_analysisform_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=250, null=True)),
                ('file', models.ImageField(upload_to='vehice_images')),
                ('desc', models.TextField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='images',
            field=models.ManyToManyField(to='backend.Img'),
        ),
    ]
