# Generated by Django 2.0.3 on 2018-11-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20181126_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='filename',
        ),
    ]
