# Generated by Django 2.0.3 on 2018-11-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_remove_img_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='responsible',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
