# Generated by Django 2.0.3 on 2018-11-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_entryform_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='company',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='entryform',
            name='no_solicitud',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
