# Generated by Django 2.0.3 on 2018-11-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20181130_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryform',
            old_name='no_solicitud',
            new_name='no_request',
        ),
    ]
