# Generated by Django 2.0.3 on 2018-12-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20181130_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='identification',
            name='temp_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
