# Generated by Django 2.0.3 on 2018-12-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_identification_temp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('analysis', models.ManyToManyField(to='backend.Exam')),
            ],
        ),
        migrations.RemoveField(
            model_name='analysisform',
            name='no_fish',
        ),
        migrations.RemoveField(
            model_name='analysisform',
            name='organs',
        ),
        migrations.RemoveField(
            model_name='cassette',
            name='identifications',
        ),
        migrations.RemoveField(
            model_name='cassette',
            name='sample_id',
        ),
        migrations.AddField(
            model_name='cassette',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='cassettes',
            field=models.ManyToManyField(to='backend.Cassette'),
        ),
        migrations.AddField(
            model_name='sample',
            name='organs',
            field=models.ManyToManyField(to='backend.Organ'),
        ),
        migrations.AddField(
            model_name='identification',
            name='samples',
            field=models.ManyToManyField(to='backend.Sample'),
        ),
    ]
