# Generated by Django 2.0.3 on 2018-12-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_auto_20181212_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identification',
            name='samples',
        ),
        migrations.AddField(
            model_name='sample',
            name='identification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Identification'),
        ),
    ]
