# Generated by Django 2.0.3 on 2018-12-12 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_auto_20181212_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='entryform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.EntryForm'),
        ),
    ]
