# Generated by Django 2.0.3 on 2018-12-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_auto_20181213_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
