# Generated by Django 2.0.3 on 2018-12-20 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_slice_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostic',
            options={'verbose_name': 'Diagnóstico', 'verbose_name_plural': 'Diagnósticos'},
        ),
        migrations.AlterModelOptions(
            name='organlocation',
            options={'verbose_name': 'Localización', 'verbose_name_plural': 'Localizaciones'},
        ),
        migrations.AlterModelOptions(
            name='pathology',
            options={'verbose_name': 'Hallazgo', 'verbose_name_plural': 'Hallazgos'},
        ),
        migrations.RemoveField(
            model_name='sample',
            name='cassettes',
        ),
        migrations.AddField(
            model_name='cassette',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Sample'),
        ),
        migrations.AddField(
            model_name='report',
            name='identification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Identification'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre del diagnóstico'),
        ),
        migrations.AlterField(
            model_name='organlocation',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre de localización'),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre del hallazgo'),
        ),
    ]
