# Generated by Django 2.0.3 on 2018-12-21 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_auto_20181220_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_findings', models.TextField(blank=True, null=True)),
                ('box_diagnostics', models.TextField(blank=True, null=True)),
                ('box_comments', models.TextField(blank=True, null=True)),
                ('analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.AnalysisForm')),
            ],
        ),
    ]
