# Generated by Django 2.0.3 on 2019-01-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_auto_20190123_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerreceptioncondition',
            name='entryform',
        ),
        migrations.RemoveField(
            model_name='entryform',
            name='questionreceptionconditions',
        ),
        migrations.AddField(
            model_name='answerreceptioncondition',
            name='identification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Identification'),
        ),
        migrations.AddField(
            model_name='identification',
            name='questionreceptionconditions',
            field=models.ManyToManyField(through='backend.AnswerReceptionCondition', to='backend.QuestionReceptionCondition'),
        ),
    ]
