# Generated by Django 2.0.3 on 2019-01-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_auto_20190123_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerreceptioncondition',
            name='identification',
        ),
        migrations.RemoveField(
            model_name='answerreceptioncondition',
            name='question',
        ),
        migrations.RemoveField(
            model_name='identification',
            name='questionreceptionconditions',
        ),
        migrations.DeleteModel(
            name='AnswerReceptionCondition',
        ),
        migrations.DeleteModel(
            name='QuestionReceptionCondition',
        ),
    ]
