# Generated by Django 2.0.3 on 2019-01-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_auto_20190124_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='identification',
            name='organs',
            field=models.ManyToManyField(to='backend.Organ'),
        ),
    ]
