# Generated by Django 2.0.3 on 2019-02-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_identification_organs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleExams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Exam')),
                ('organ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Organ')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Sample')),
            ],
        ),
    ]
