# Generated by Django 2.0.3 on 2019-02-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_SampleChanges'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.IntegerField(choices=[(1, 'Histológicos'), (2, 'No histológicos'), (3, 'Planimetrías')], default=1),
        ),
    ]
