# Generated by Django 2.0.3 on 2019-05-07 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0051_analysisform_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='exams',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='organs',
        ),
        migrations.AddField(
            model_name='sampleexams',
            name='patologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
