# Generated by Django 2.0.3 on 2019-05-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_ExamPatologo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfinal',
            name='no_reporte',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
