# Generated by Django 2.0.3 on 2019-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_ExamPatologo'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisform',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
