# Generated by Django 2.0.3 on 2020-03-02 18:13

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_Responsible'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('body', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_file', models.FileField(upload_to=backend.models.entry_files_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.EmailTemplate')),
            ],
            options={
                'verbose_name': 'Email Adjunto',
                'verbose_name_plural': 'Email Adjuntos',
            },
        ),
        migrations.AlterModelOptions(
            name='responsible',
            options={'verbose_name': 'Responsable', 'verbose_name_plural': 'Responsables'},
        ),
    ]
