# Generated by Django 2.0.3 on 2020-03-03 19:18

import backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0056_EmailTemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentResumeVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entryform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.EntryForm')),
            ],
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='emailtemplateattachment',
            name='template_file',
            field=models.FileField(upload_to=backend.models.entry_files_directory_path, verbose_name='Archivo Adjunto'),
        ),
    ]
