# Generated by Django 2.0.3 on 2020-03-12 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0057_DocumentVersion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=250, null=True)),
                ('file', models.FileField(blank=True, upload_to='resume_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lang', models.IntegerField(choices=[(1, 'es'), (2, 'en')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentResumeActionLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_action', models.BooleanField()),
                ('download_action', models.BooleanField()),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.DocumentResume')),
                ('done_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='documentresumeversion',
            old_name='created_at',
            new_name='generated_at',
        ),
        migrations.RenameField(
            model_name='documentresumeversion',
            old_name='created_by',
            new_name='generated_by',
        ),
        migrations.AddField(
            model_name='documentresume',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.DocumentResumeVersion'),
        ),
    ]
