# Generated by Django 2.0.3 on 2020-03-16 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0058_auto_20200312_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCaseResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=250, null=True)),
                ('file', models.FileField(blank=True, upload_to='resume_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lang', models.IntegerField(choices=[(1, 'es'), (2, 'en')], default=1)),
                ('version', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentResumeActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_action', models.BooleanField()),
                ('download_action', models.BooleanField()),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.DocumentCaseResume')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentresume',
            name='version',
        ),
        migrations.RemoveField(
            model_name='documentresumeactionlogs',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentresumeactionlogs',
            name='done_by',
        ),
        migrations.RenameModel(
            old_name='DocumentResumeVersion',
            new_name='CaseVersion',
        ),
        migrations.DeleteModel(
            name='DocumentResume',
        ),
        migrations.DeleteModel(
            name='DocumentResumeActionLogs',
        ),
        migrations.AddField(
            model_name='documentcaseresume',
            name='case_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.CaseVersion'),
        ),
        migrations.AddField(
            model_name='documentcaseresume',
            name='entryform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.EntryForm'),
        ),
        migrations.AddField(
            model_name='documentcaseresume',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
