# Generated by Django 2.0.3 on 2020-03-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_auto_20200316_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentresumeactionlog',
            old_name='generated_by',
            new_name='done_by',
        ),
        migrations.AlterField(
            model_name='documentresumeactionlog',
            name='download_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentresumeactionlog',
            name='mail_action',
            field=models.BooleanField(default=False),
        ),
    ]
