# Generated by Django 2.0.3 on 2020-03-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_auto_20200316_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcaseresume',
            name='file',
            field=models.FileField(blank=True, upload_to='pdfs'),
        ),
    ]
