# Generated by Django 2.0.3 on 2020-04-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_entryform_anamnesis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
    ]
