# Generated by Django 2.0.3 on 2020-04-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_auto_20200414_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='organ_type',
            field=models.IntegerField(choices=[(1, 'Órgano por sí solo'), (2, 'Conjunto de órganos')], default=1, max_length=1, verbose_name='Tipo'),
        ),
    ]
