# Generated by Django 2.0.3 on 2020-04-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_auto_20200414_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='service',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Service', verbose_name='Tipo de Servicio'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='organ_type',
            field=models.IntegerField(choices=[(1, 'Órgano por sí solo'), (2, 'Conjunto de órganos')], default=1, verbose_name='Tipo'),
        ),
    ]
