# Generated by Django 2.0.3 on 2020-04-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_auto_20200415_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vehice_external_reports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='analysisform',
            name='external_reports',
            field=models.ManyToManyField(to='backend.ExternalReport'),
        ),
        migrations.AddField(
            model_name='analysisform',
            name='service_comments',
            field=models.ManyToManyField(to='backend.ServiceComment'),
        ),
    ]
