# Generated by Django 2.0.3 on 2020-04-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_auto_20200423_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='organs',
            field=models.ManyToManyField(to='backend.Organ'),
        ),
    ]
