# Generated by Django 2.0.3 on 2020-04-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_auto_20200423_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Sample'),
        ),
        migrations.RemoveField(
            model_name='cassette',
            name='sample',
        ),
        migrations.AddField(
            model_name='cassette',
            name='sample',
            field=models.ManyToManyField(to='backend.Sample'),
        ),
    ]
