# Generated by Django 2.0.3 on 2020-04-29 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_auto_20200429_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slice',
            name='sample',
        ),
        migrations.AddField(
            model_name='report',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Sample'),
        ),
    ]
