# Generated by Django 2.0.3 on 2020-06-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0079_entryform_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='entryform_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.EntryForm_Type'),
        ),
    ]
