# Generated by Django 2.0.3 on 2020-07-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_auto_20200619_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='pathologists_assignment',
            field=models.BooleanField(default=True, verbose_name='Asignación de patólogo'),
        ),
    ]
