# Generated by Django 2.0.3 on 2020-07-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_exam_pathologists_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='cage',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='extra_features_detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='group',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='no_container',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='no_fish',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='observation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='temp_id',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='weight',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
