# Generated by Django 2.0.3 on 2020-07-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0084_identification_removable'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisform',
            name='assignment_comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='analysisform',
            name='assignment_deadline',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
