# Generated by Django 2.0.3 on 2020-08-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0085_auto_20200730_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisform',
            name='manual_cancelled_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='analysisform',
            name='manual_closing_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
