# Generated by Django 2.0.3 on 2020-08-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0087_analysisform_assignment_done_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisform',
            name='pre_report_end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='analysisform',
            name='pre_report_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysisform',
            name='pre_report_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='analysisform',
            name='pre_report_started',
            field=models.BooleanField(default=False),
        ),
    ]
