# Generated by Django 2.0.3 on 2020-09-11 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0091_auto_20200908_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailccto',
            options={'verbose_name': 'Destinatario copiado en Plantilla Email', 'verbose_name_plural': 'Destinatarios copiados en Plantilla Email'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': 'Plantilla Email', 'verbose_name_plural': 'Plantillas Emails'},
        ),
        migrations.AddField(
            model_name='entryform',
            name='research_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Research'),
        ),
        migrations.AlterField(
            model_name='research',
            name='status',
            field=models.BooleanField(default=False, verbose_name='¿Activo?'),
        ),
    ]
