# Generated by Django 2.0.3 on 2020-09-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0092_auto_20200911_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='score_diagnostic',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='entryform',
            name='score_report',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
