# Generated by Django 2.0.3 on 2020-10-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0095_exam_pricing_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Abreviatura (ESP)'),
        ),
        migrations.AddField(
            model_name='organ',
            name='abbreviation_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Abreviatura (EN)'),
        ),
        migrations.AddField(
            model_name='organ',
            name='name_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre (EN)'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre (ESP)'),
        ),
    ]
