# Generated by Django 2.0.3 on 2020-11-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0096_auto_20201021_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisform',
            name='score_diagnostic',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='analysisform',
            name='score_report',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
