# Generated by Django 2.0.3 on 2020-11-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0097_auto_20201103_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tinción',
                'verbose_name_plural': 'Tinciones',
            },
        ),
        migrations.RemoveField(
            model_name='entryform',
            name='score_diagnostic',
        ),
        migrations.RemoveField(
            model_name='entryform',
            name='score_report',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='stain',
        ),
    ]
