# Generated by Django 2.0.3 on 2020-11-13 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0098_auto_20201113_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='stain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Stain', verbose_name='Tinción'),
        ),
    ]
