# Generated by Django 2.0.3 on 2020-11-16 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0099_exam_stain'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisform',
            name='stain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Stain', verbose_name='Tinción'),
        ),
        migrations.AddField(
            model_name='stain',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Abreviación'),
        ),
    ]
