# Generated by Django 2.0.3 on 2020-11-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0100_auto_20201116_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisform',
            name='stain',
        ),
        migrations.AddField(
            model_name='sampleexams',
            name='stain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Stain', verbose_name='Tinción'),
        ),
    ]
