# Generated by Django 2.0.3 on 2020-12-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0101_auto_20201117_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisform',
            name='stain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Stain', verbose_name='Tinción'),
        ),
    ]
