# Generated by Django 2.0.3 on 2021-01-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0104_auto_20210115_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='responsible',
            new_name='client_responsible',
        ),
        migrations.AddField(
            model_name='research',
            name='vehice_responsible',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
