# Generated by Django 2.0.3 on 2021-01-15 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0105_auto_20210115_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='client_responsible',
        ),
        migrations.RemoveField(
            model_name='research',
            name='vehice_responsible',
        ),
        migrations.AddField(
            model_name='research',
            name='external_responsible',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Responsable Externo'),
        ),
        migrations.AddField(
            model_name='research',
            name='internal_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsable Interno'),
        ),
    ]
