# Generated by Django 2.0.3 on 2021-01-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0106_auto_20210115_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='transfer_order',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
