# Generated by Django 2.0.3 on 2021-01-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0107_entryform_transfer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='entry_format',
            field=models.IntegerField(choices=[(1, 'Tubo'), (2, 'Cassette'), (3, 'Bloque'), (4, 'Slide s/teñir'), (5, 'Slide teñido'), (6, 'Vivo'), (7, 'Muerto')], default=1),
        ),
    ]
