# Generated by Django 2.0.3 on 2021-02-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0108_entryform_entry_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='identification',
            name='correlative',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='identification',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
