# Generated by Django 2.0.3 on 2021-03-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0110_auto_20210316_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlative', models.IntegerField(blank=True, default=1, null=True)),
                ('identification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Identification')),
                ('organs', models.ManyToManyField(to='backend.Organ')),
            ],
        ),
    ]
