# Generated by Django 2.0.3 on 2021-03-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0111_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='client_case_number',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
