# Generated by Django 2.0.3 on 2021-03-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0113_auto_20210317_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='organs',
            field=models.ManyToManyField(through='backend.OrganUnit', to='backend.Organ'),
        ),
    ]
