# Generated by Django 2.0.3 on 2021-03-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0114_unit_organs'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='samples',
            field=models.ManyToManyField(to='backend.Sample'),
        ),
    ]
