# Generated by Django 2.0.3 on 2021-03-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0115_unit_samples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='samples',
        ),
        migrations.AddField(
            model_name='sample',
            name='units',
            field=models.ManyToManyField(to='backend.Unit'),
        ),
    ]
