# Generated by Django 2.0.3 on 2021-03-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0116_auto_20210321_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='units',
        ),
        migrations.AddField(
            model_name='sample',
            name='organs',
            field=models.ManyToManyField(to='backend.Organ'),
        ),
    ]
