# Generated by Django 2.1.15 on 2021-05-22 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0118_auto_20210506_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Laboratorio de Ingreso',
            },
        ),
        migrations.AddField(
            model_name='entryform',
            name='laboratory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Laboratory'),
        ),
    ]
