# Generated by Django 2.1.15 on 2021-05-28 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0119_auto_20210522_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField()),
                ('modelo', models.IntegerField(blank=True, null=True)),
                ('id_modelo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='organsUnits',
            field=models.ManyToManyField(to='backend.OrganUnit'),
        ),
        migrations.AddField(
            model_name='log',
            name='log_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.LogType', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
