# Generated by Django 2.1.15 on 2021-06-13 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0120_auto_20210528_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='organsUnits',
            new_name='unit_organs',
        ),
        migrations.AlterField(
            model_name='sample',
            name='identification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Identification'),
        ),
    ]
