# Generated by Django 2.1.15 on 2021-06-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0121_auto_20210613_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='organs',
        ),
    ]
