# Generated by Django 2.1.15 on 2021-06-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0122_remove_sample_organs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleexams',
            name='unit_organ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.OrganUnit'),
        ),
    ]
