# Generated by Django 2.1.15 on 2021-07-02 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0123_sampleexams_unit_organ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisform',
            name='external_reports',
            field=models.ManyToManyField(blank=True, to='backend.ExternalReport'),
        ),
        migrations.AlterField(
            model_name='analysisform',
            name='manual_cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisform',
            name='patologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisform',
            name='researches',
            field=models.ManyToManyField(blank=True, to='backend.Research'),
        ),
        migrations.AlterField(
            model_name='analysisform',
            name='service_comments',
            field=models.ManyToManyField(blank=True, to='backend.ServiceComment'),
        ),
        migrations.AlterField(
            model_name='analysisform',
            name='stain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Stain', verbose_name='tinción'),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='attached_files',
            field=models.ManyToManyField(blank=True, to='backend.CaseFile'),
        ),
    ]
