# Generated by Django 2.1.15 on 2021-08-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0125_entryform_sampled_at_am_pm'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='sampled_at_hour',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
