# Generated by Django 2.1.15 on 2021-08-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0126_entryform_sampled_at_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryform',
            name='sampled_at_hour',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
