# Generated by Django 3.1.13 on 2021-09-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0128_auto_20210824_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='is_optimum',
            field=models.BooleanField(null=True),
        ),
    ]
